services:
  # Backend API service
  - type: web
    name: resumate-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt && python -m spacy download en_core_web_sm
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000

  # Frontend service
  - type: web
    name: resumate-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        value: https://resumate-api.onrender.com 